spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reptile
    username: root
    password: wcj520600
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: localhost
#    port: 6379
#    password: wcj520600