spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reptile
    username: root
    password: wcj520600
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      enable: true
  redis:
    host: localhost
    port: 49153
    password: redispw
    lettuce:
      pool:
        enabled: true
mybatis-plus:
  global-config:
    banner: false